/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Bill;

import dao.BillDAO;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Bill;
import model.User;

/**
 *
 * @author DELL
 */
public class SearchBillFrm extends javax.swing.JFrame implements ActionListener{
    private ArrayList<Bill> listBill;
    private JTextField txtKey;
    private JButton btnSearch;
    private JTable tblResult;
    private User user;
    private SearchBillFrm mainFrm;
//	
    /**
     * Creates new form SearchBillFrm
     */
   
    public SearchBillFrm(User user) {
        super("Search room to edit");
            this.user = user;
            mainFrm = this;
            listBill = new ArrayList<Bill>();

            JPanel pnMain = new JPanel();
            pnMain.setSize(this.getSize().width-5, this.getSize().height-20);		
            pnMain.setLayout(new BoxLayout(pnMain,BoxLayout.Y_AXIS));
            pnMain.add(Box.createRigidArea(new Dimension(0,10)));

            JLabel lblHome = new JLabel("Search a room to edit");
            lblHome.setAlignmentX(Component.CENTER_ALIGNMENT);	
            lblHome.setFont (lblHome.getFont ().deriveFont (20.0f));
            pnMain.add(lblHome);
            pnMain.add(Box.createRigidArea(new Dimension(0,20)));

            JPanel pn1 = new JPanel();
            pn1.setLayout(new BoxLayout(pn1,BoxLayout.X_AXIS));
            pn1.setSize(this.getSize().width-5, 20);
            pn1.add(new JLabel("Room name: "));
            txtKey = new JTextField();
            pn1.add(txtKey);
            btnSearch = new JButton("Search");
            btnSearch.addActionListener((ActionListener) this);
            pn1.add(btnSearch);
            pnMain.add(pn1);
            pnMain.add(Box.createRigidArea(new Dimension(0,10)));

            JPanel pn2 = new JPanel();
            pn2.setLayout(new BoxLayout(pn2,BoxLayout.Y_AXIS));		
            tblResult = new JTable();
            JScrollPane scrollPane= new  JScrollPane(tblResult);
            tblResult.setFillsViewportHeight(false); 
            scrollPane.setPreferredSize(new Dimension(scrollPane.getPreferredSize().width, 250));

            tblResult.addMouseListener(new MouseAdapter() {
                    public void mouseClicked(MouseEvent e) {
                            int column = tblResult.getColumnModel().getColumnIndexAtX(e.getX()); // get the coloum of the button
                            int row = e.getY() / tblResult.getRowHeight(); // get the row of the button

                            // *Checking the row or column is valid or not
                            if (row < tblResult.getRowCount() && row >= 0 && column < tblResult.getColumnCount() && column >= 0) {
                                    (new BillInfoFrm(user, listBill.get(row))).setVisible(true);
                                    mainFrm.dispose();
                            }
                    }
            });

            pn2.add(scrollPane);
            pnMain.add(pn2);	
            this.add(pnMain);
            this.setSize(600,300);				
            this.setLocation(200,10);
            this.setVisible(true);
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton btnClicked = (JButton)e.getSource();
        if(btnClicked.equals(btnSearch)){
                if((txtKey.getText() == null)||(txtKey.getText().length() == 0))
                        return;
                BillDAO bd = new BillDAO();
                listBill = bd.searchBill(txtKey.getText().trim());

                String[] columnNames = {"Id", "Month", "Client Name", "Status"};
                String[][] value = new String[listBill.size()][5];
                for(int i=0; i<listBill.size(); i++){
                        value[i][0] = listBill.get(i).getId() +"";
                        value[i][1] = listBill.get(i).getMonth() + "";
                        value[i][2] = listBill.get(i).getContract().getClient().getName();
                        if(listBill.get(i).isBillStatus()){
                            value[i][3] = "Đã trả";
                        }else{
                            value[i][3] = "Chưa trả";
                        }
                }
                DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                       //unable to edit cells
                       return false;
                    }
                };
                tblResult.setModel(tableModel);
        }
    }
}
